language: python
cache: pip
python:
- '2.7'
install:
- pip install -r requirements.txt
before_script:
- sh init.sh
script:
- pep8 --exclude=*/migrations/,A2A .
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: TsBqZ1S0y34joO59rimG3XTro5BgfaReChcDdwZ6/7Sg9PWwJF1d25ytcEYUr/SViC6B0+qMVMPY/LTRKpYaH5irHjeoeSlrDobTxjgGa2kNsy+VSvLuzodnGCgXhUGoH+Z/GNmmbH/LCo1YR7bRjQ17Ja+OubZigDYOJDBZXCzqS6dBKt1YcVmz5DBu9QQb6Yvt0cuQQk9yLFHnvxdVHSnjUAm/plufvr0GnE+Igv/HbvGY6joqN4pg3qzLFp19G3rPxV1gPZXqWQ9IQr9mnHx0QLuZn9DxTSbYYf/0Iet2zjjgCBpebc8H8pHIae76Vcx0ssVJ5RDWjRPhFVYhuT01FMbKnPYITmbPzXny9DXvVtsnhWeKYlQPKYTsbrh67jDJM16D2vWsmSOUbYu/x9QIexut1yYSJYPMl2IYWw4RmeKUZFiSJEH+MoGclUFeBy0hG5uo5mRE17/2it6M+wNI44c6U3YO5A2TdR9gck0+muxb1AQA62rg64dveM3pOX9Qc43VnDxKw+ddx6m3v6iA/nVcL74zoRj8QUHHYmUX/N5dJN6qCBfFT+haeeoFkDTZm4cTP8JhSKH7MegDDZNN5+BhuZCTUjS46eu7rVb8zV/sqCfPVUL73niWi8LabpDU9kzN34RKA8MTy/8T8bMAoojhjBnwXEBDG4Qozz4=
  strategy: git
  app: tech2016
  on:
    repo: namnd95/tech2016
    branch: TestingCI
