language: python
cache: pip
python:
- '2.7'
install:
- pip install -r requirements.txt
before_script:
- sh init.sh
script:
- pep8 --exclude=*/migrations/,A2A .
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: lj7XpKqdmv3rEsMl0fl3pTezLKnJaLP2byE0qnf0b10ldGP+Kbb042ZuuAtvHvlmRMsCOG2Sm0CGm3kN5Tz6dVwpox6gW1VqUczGOQSDo7zDA+Q9VyG3aQpBCP432by2g1Vz+hLz+8i7sLmStmF32GAx+qIiX9sLboQ8pCktUQK/6xbZWHgJH3NC5sKxthvt6s+bsiji50oyFAI2eDPUlc2t/Wu0Me3VzLGNdmtEM6oDat3j5DrEWK7hh8Fokpsk/Pxpv8z/VW/uWmIFB+VkT5XtD5IAYeeWRih7gL9MdQnI95XwYWT2fOC5bBFExInqqTCl+MSlBDCM1CsBV/9saku1IWVtlas9eLmu32wwiv7GDtbAQsISIgpFMC+47Gc9TCni42RQJa7ymGhq/fM/Q6FltktGan80HOQR+YVGSIHaxX9GCsEkcItfUCpRoxO2vM0VMQIvJiVHo+3C5eq5so0slx0peGE4qBPomkh0Fisy8iAv7m6eZttpr7vks5BMCfyIbA+ivlYOgCz6a62vVZvUIxwZoZAcG4XHo9vg/K4krDAdK6IqlXi1R1GgvV/ycv1SPX76+YjfmlX+T3mhzLWijziKUdYnGsiOV4FYFyexSLBo94lk5Aal8b6tJjtMAsrP58GDS5kqmKCx88KXRNcM4y7nvnKjA3/Mmyn2GIw=
  strategy: git
  app: tech2016
  on:
    repo: namnd95/tech2016
    branch: TestingCI
