language: python
cache: pip
python:
- '2.7'
install:
- pip install -r requirements.txt
before_script:
- sh init.sh
script:
- pep8 --exclude=*/migrations/,A2A .
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Udumq3xC2bGDVGqttVN9IgpxAb8ZeWohomhLdMq3zMWjKi8NRAMgqcUfJLJtaLbYdFDm9fVKjPuSh9bBPOGQ52LbRWA+muMpe4mqIWc0WDsSkt03GTdwbhoSqIZZDypwgFhxFD50e5MlP/mDZgujNoTKlQVWxCKw/cqvY8/vH8mASFvPs8fCyMILeGV0eQmiN4nHRs/z06xyUJxCIuJ1sS12j2nkOjrEYkcC8rgC223G5kcBiP6H7lPjnNp0BQ2c8R3Dfw79BzC0WgXXecVRaUWkaNUpz2/CUPgCCpb1dToYAUflVz6j5/2YwzsUIee0xGhZafi8m4RoYbaD5/M/y7E6ets4L+0Qo1SBFEmUIiGUCA1dEZGYkJrw0V0OZUddiv6KF2wBITQybAkmSXekIRv3Z/yGP033Nfd63l1qgiNMU9Iw0m/jghQKkN3PhZJagng5AM/HvUUK5n4/bAWMli/XI6vJeElDRlC6MDUCzR+CHtwYdJO7yWzT/sXYS6Ssvu3sMwiL0fKpw+7IVgcpEjZZ+yDMd7tCWirVCyN3AFA4P2r+nYzeNCwo0YsO6wZTgj7BDQtTXauPKXfoLVRZhGKkVUEnMdGJTBN8bYfmiZNTcQ0dwLQsug9TwS1FV3HqVx5Nx4repYwy4qLMAwFey7yeG99atGVhY4WHQqiEDcc=
  run:
    - "sh init.sh"
  strategy: git
  app: tech2016-test
  on:
    repo: namnd95/tech2016
    branch: TestingCI
